### PR TITLE
Location info for Attributes

### PR DESCRIPTION
**Pull request by sakagg**
Provides locations information for Attributes.
Can be accessed from the `location` object of every attribute(.attrs list)
eg: <pre>&lt;img src=""&gt;
     |    |
  start end</pre>

### CODE REVIEW

**Comment by inikulin** [comment]
Wow, thank you for this! The only concerns I have is about performance since you've introduced `_leaveAttrName'. Can you run regression benchmark, please?

**Comment by inikulin** [comment]
Oh, and seems like it will not work for the `htmlparser2` tree adapter, since it doesn't have `node.attrs` and uses `node.attribs` dictionary instead. Taking in the account differences between attributes representation in tree adapters I think we should move location info to the start tag's 'location` object (for SAX parser and Tokenizer) and into the node's `__location` (for Parser). E.g.:
```js
startTag.location = {
    start: 0,
    end: 25,
    attrs: {
        'style': {
            start: 4,
            end: 12
         },
         'href': {
          ...
         }
    }
};
```  

and

```js
node.__location = {
    start: 0,
    end: 25,
    startTag: {
        ...
    },
    endTag: {
        ...
    },
    attrs: {
        'style': {
            start: 4,
            end: 12
         },
         'href': {
          ...
         }
    }
};
```

**Comment by stevenvachon** [comment]
+1

**Comment by sakagg** [comment]
Sorry, I've been busy lately because of college work!
I'll get back to this in a few days if it's okay.

**Comment by inikulin** [comment]
@sakagg Sure! Note: I've landed some v2.0-related commits recently. Could you rebase you work on top of it?

**Comment by stevenvachon** [comment]
+1

**Comment by stevenvachon** [comment]
:-1:

**Comment by inikulin** [comment]
Closing in favor of #92

**Comment by sakagg** [comment]
Good thing someone finally did it!
Thanks @yyx990803

**Pull request closed without merging**
