### PR TITLE
grammar fix in api docs

### PR DESCRIPTION
**Pull request by stevenvachon**
Minor change. I think that a link to a wiki page/etc explaining just how and what non-conformities can occur would be helpful. I'm even wondering as you read this.

### CODE REVIEW

**Comment by inikulin** [comment]
Thank you, I'm currently switching to the jsdoc auto-generated docs. So, fix appropriate doc comments instead of README, please: 
 * https://github.com/inikulin/parse5/blob/master/lib/parser/index.js#L23
 * https://github.com/inikulin/parse5/blob/master/lib/serializer/index.js#L16

>  I think that a link to a wiki page/etc explaining just how and what non-conformities can occur would be helpful.

Well, it will obviously not parse/serialize HTML entities how spec suggests.

**Comment by stevenvachon** [comment]
Obvious to whom? Not to me.

Corrections made.

**Comment by inikulin** [comment]
Gosh, that's why I hate all this optional spec violations and other weird edge case things: it's not enough to tell people what they can mess up everything, you should describe in greater detail what could possibly go wrong. And nearly as always the answer is: **anything, except your edge case scenario for which we've implemented this options**.

So the answer is: anything, except edge case scenarios for which we've implemented this options (#31). E.g.: running serializer with `encodeHtmlEntities` enabled on the output of parser with the `decodeHtmlEntities` disabled: `&amp;` will be serialized as `&amp;amp;`

**Comment by inikulin** [comment]
Thank you!

**Comment by stevenvachon** [comment]
Dude, we don't all write and maintain spec-compliant HTML parsers. If we did, you wouldn't need to write one.

The browser decodes and encodes entities within attributes. It probably does so for text content as well so that it can render, but web inspectors re-encode them for easy reading.

With this new knowledge, I agree that `decodeHtmlEntities` should probably be removed. A note regarding manual re-encoding would be helpful to those looking to skip decoding.

**Pull request merged**
