### PR TITLE
chore(package): Bump versions to 7.0.0

### PR DESCRIPTION
**Pull request by fb55**
This has to be done as a PR due to branch protection.

### CODE REVIEW

**Review by wooorm — APPROVED** [review]
Exciting! :+1:

Do you know how you’re about to publish?

**Comment by fb55** [comment]
> Do you know how you’re about to publish?

I only know about `npm publish --workspaces`. Any tricks you can share on top of that?

**Comment by wooorm** [comment]
Yeah :+1: Also, you might want to tag the commit, if you can. They use a `v` prefix here: https://github.com/inikulin/parse5/releases.

**Comment by fb55** [comment]
Published all packages. I had to manually remove some files before publishing, as I couldn't get ignore patterns to properly work before publishing (see #510).

Release notes are at https://github.com/inikulin/parse5/releases/tag/v7.0.0. Please let me know if there is anything you'd like to change!

**Comment by wooorm** [comment]
That’s a lot! What I like about it, is that all the information that people need, is there. I do think it can be restructured and improved somewhat.

- Things like `1.45x` are hard to understand. is that 45% faster? More than twice as fast?
- There is too much emphasis: there are many links, many numbers, whole strong sentences. When everything is marked up as important, nothing is important anymore. This can be solved by improving the structure of the entry, I believe

Let me try and see if I can reword it, I’ll post it here.

P.S. Lastly, personally, I believe I’ve expressed this before but I want to stress it, I find the docs very bad. There are only types (and some barely readable prose extracted from them, and out-of-date examples). I think it’s important to prioritize how a newcomer goes from seeing this repo to using the project.

**Comment by fb55** [comment]
> Things like 1.45x are hard to understand. is that 45% faster? More than twice as fast?

This is this ratio: https://github.com/inikulin/parse5/blob/abec4c2be40f09dc4e3d0fd6a64eb10bbb24cca0/bench/perf/index.js#L79

> There is too much emphasis

I see your point. I tried working around this via headings, but there definitely is room for improvement. Curious to see where you end up!

> I find the docs very bad

I agree with this. The only reason I pushed for TypeDoc is that manually managing Markdown files generated by TypeDoc is strictly inferior to managing source code, which then use TypeDoc to generate documentation (because information is otherwise duplicated, colocation makes a need for updates more evident etc.).

For me, the main thing I'd like to see in terms of documentation are some guides, which explain how to use each of the packages in this repo. Do you have something you'd prioritise instead?

**Comment by wooorm** [comment]
How about this? This is what I’d go with. But you know much more about this project than I so I might be missing or misrepresenting important things.

In particular, I have two inline questions for the last two `Potentially breaking changes` points.

Also: this displays here differently that in the release (notably heading size). Please preview there to see how it will end up exactly!

```
Welcome to `parse5@7`! ✨ This is a big release with many improvements but also some breaking changes.

`parse5` is now maintained by the community (more who’s who below). **We need your support to continue the project!** You can help us out financially on [OpenCollective](https://opencollective.com/parse5) or help out on the issues.

#### In short

* ESM
* TypeScript
* HTML spec updates
* Performance improvements (±50-150% faster)

#### Breaking: ESM

The packages are now ESM. We’ve shipped dual packages for `parse5` and `parse5-htmlparser2-tree-adapter` for now though. To migrate, please read [this Gist](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) on how to update.
Note that private internals are no longer available.

*Implemented by @43081j in #351*

#### Breaking: TypeScript

The codebase is now in TypeScript, which uncovered many bugs, and resulted in much improved types. To migrate, please remove `@types/parse5*` as we now ship our own types.

*Implemented by @fb55 in #362*

#### Potentially breaking changes

* Update to match changes in HTML spec (#442, #451)
* Remove `parse5-serializer-stream` (**to do: how to migrate**) (#481)
* ?? The rewriting stream now splits very long text sections (#434) and doesn’t escape text in special tags anymore (#434) (**to do: what does this mean and how to migrate**)
* ?? The htmlparser2 adapter now uses `domhandler`’s node interface (#327) (**to do: how is this breaking? how to migrate**)

#### Other changes

* **minor** add hooks for stack events to tree adapter interface #385
* **minor** add support for fragments in `parse5-parser-stream` #487
* **minor** add `serializeOuter` (like `.outerHTML`), `scriptingEnabled` option #383
* **patch** fix parsing of `<<` in comments parsed wrongly as `<!` (#326)
* **patch** fix position of `endTag` for mixed-case foreign elements (#353)
* **patch** fix position of `html`, `body` in edge cases (#436)
* docs: parse5 has a new documentation website at [`parse5.js.org`](http://parse5.js.org/) #443

We’ve also changed the hidden internals. You probably don’t use those. But if you’re wondering:

<details><summary>Show internal changes</summary>

* Use state machine pattern from htmlparser2 in tokenizer [`5d7a780` (#362)](https://github.com/inikulin/parse5/pull/362/commits/5d7a780b70d3669def4c6bb20cbec816804d44a5)
* Replace token queue with callbacks (#404, #405, #419)
* Use callbacks in `OpenElementStack` #429
* Remove mixins (as part of #362)
* Remove `getNextToken` #461
* Remove `_bootstrap` parse method #384
* Drop chunks from the tokenizer right when they are emitted #432
* Change from class in serializer #383
* Use [`entities`](https://github.com/fb55/entities) module for encoding and decoding entities ([`2b92054` (#362)](https://github.com/inikulin/parse5/pull/362/commits/2b9205458b9305de1406966568567ccfc1633fa1), #486) 

</details>

#### New contributors

Thanks @anko, @TrySound, @samouri, @alan-agius4, @pmdartus!

**Full changelog**: https://github.com/inikulin/parse5/compare/v6.0.1...v7.0.0
```

**Comment by wooorm** [comment]
(note: I forgot the `community` bit at the bottom first)

**Comment by fb55** [comment]
Great rewrite — I've adopted most of the changes.

**Pull request merged**
