### PR TITLE
feat(parser): Support search element

### PR DESCRIPTION
**Pull request by fb55**
Not sure if this PR should be merged at this time.

The `<search>` element is tested in `html5lib-tests`, but the PR for the spec hasn't been merged yet (https://github.com/whatwg/html/pull/7320). It seems like there is consensus around this spec change (see https://github.com/whatwg/html/issues/7581), but we might hold off on this until the spec has actually been updated.

### CODE REVIEW

**Review by wooorm — COMMENTED** [review]
LGTM but weird to merge something that isn’t in HTML.
Is there a way for the tests to only test what is merged?
If not, should such a “feature-flag” be proposed there?

**Comment by fb55** [comment]
It is a bit odd that this was already added to `html5lib-tests`. I will hold out on merging until the spec change has been merged.

**Comment by Kaleidea** [comment]
> I will hold out on merging until the spec change has been merged.

Hello @fb55, I'm the software architect who implemented the `search` element for the 3 main browsers. FYI the spec has been in W3C TAG review stage for 2 months and it's very likely to take much more time as fundamental steps in the standardization guideline were missed and the result does not meet the web platform design principles yet. There is no consensus so far on how to resolve those details.

Nevertheless, as I see those details won't affect your PR.
Yours sincerely.

**Comment by fb55** [comment]
@Kaleidea Thanks a lot for the context!

**Comment by fb55** [comment]
The search element is now part of the HTML spec, so let's get this merged!

**Review by wooorm — APPROVED** [review]
Yep!! :)

**Pull request merged**
