### PR TITLE
fix: don't generate sourcemap on build, close #831

### LINKED ISSUE #831: Failed to parse source map ...
I am using parse5 in a react app, and the modules are referring to a sourceMap file that is not being found, which is interrupting the build of the app.

I can confirm checking the dist/index.js in npm

Line 45
```js
//# sourceMappingURL=index.js.map
```

however, there isn't such file relative to path

### PR DESCRIPTION
**Pull request by antfu**
I am not sure if sourcemaps are used somewhere, but since it's not shipped with the npm, I think it's better to not generate them otherwise would lead to hanging sourcemap reference #831

### CODE REVIEW

**Comment by 43081j** [comment]
makes sense to me but have added felix as a reviewer as he might know more

**Comment by wooorm** [comment]
The code here might also be because it was intended to publish declaration/source maps, right? Could solving that by adding it to “files” also solve your issue?

**Comment by antfu** [comment]
The previous PR trying that way gets closed:
https://github.com/inikulin/parse5/pull/890#issuecomment-1503282366

I don't mind either ways - it's just the current state causing build tools like Vite emits a lot of warnings

**Comment by fb55** [comment]
Thanks @antfu!

**Comment by JvanderHeide** [comment]
Could we get a release for this?

**Pull request merged**
