### PR TITLE
Closes: #349 - Fix issues when BOM is before TAG

### PR DESCRIPTION
**Pull request by frank-dspeed**
Added Test and all other needed info the issue has the rest of the information
Closes: #349

### CODE REVIEW

**Comment by frank-dspeed** [comment]
Closes: #349

**Comment by fb55** [comment]
This doesn't seem to be in line with the spec: https://html.spec.whatwg.org/#event-stream-interpretation

> The UTF-8 decode algorithm strips one leading UTF-8 Byte Order Mark (BOM), if any.

It sounds like this should be done when decoding the original byte stream. This is implemented eg. in https://github.com/jsdom/whatwg-encoding

**Comment by frank-dspeed** [comment]
@fb55 what changes would you propose ? while keeping it working?

**Comment by fb55** [comment]
I would point users at whatwg-encoding if they are parsing content that isn't properly decoded yet. BOMs are a concern of a different part of the stack and out of scope for this library imho.

I am now thinking about adding a method to `cheerio` that allows users to load a buffer, which includes the `whatwg-encoding` module. I've opened https://github.com/cheeriojs/cheerio/issues/2051 to track this.

**Comment by frank-dspeed** [comment]
@fb55 i agree that was my conclusion also over the long run to put that into a file loading layer! as that is a problem with files not with strings as strings normaly do not contain boms normaly.

but preserving and handling the BOM as whitespace does not hurt and preserves the position data which is also a strong coupled part at present

i still have a hard time to decouple the position counting and that is file based.

when we think about scenarios where we have a input file that contains a bom then the bom can not be save stripped. without messing up the position data "sourceCodeLocationInfo"

**Comment by frank-dspeed** [comment]
# So Short Story at point of time this is the right thing to do out of my view

**Comment by frank-dspeed** [comment]
@fb55 i would love if you could give me some feedback about my thinking process as i value your work.

**Comment by fb55** [comment]
I think this is where we have slightly different ideas of what this module should be. To me, `parse5` is the module that closely follows the HTML spec and doesn't show any behaviour that isn't part of the spec.

> over the long run to put that into a file loading layer

That file loading layer already exists, with https://github.com/jsdom/whatwg-encoding and https://github.com/jsdom/html-encoding-sniffer. These follow the [WHATWG Encoding Standard](https://encoding.spec.whatwg.org/), which further guarantees compatibility with browsers. JSDom is using it, and it seems easy enough to add it to eg. Cheerio as well.

**Comment by frank-dspeed** [comment]
@fb55 ok so i will revert that and add a option to Handle BOM as WhiteSpace and without that it get stripped with warning or error? 

What would be the correct behavior stripping it complet or not handle it at all? Should it get Replaced?

**Pull request closed without merging**
