### PR TITLE
Make the readme.md actual markdown

### PR DESCRIPTION
**Pull request by Pomax**
Also, added a link directly to the API docs because those were missing for some reason.

### CODE REVIEW

**Comment by inikulin** [comment]
Hi, thanks for the contribution, but it was not intentionally not an "actual" markdown, because the "actual" markdown now looks like this:
image

**Comment by inikulin** [comment]
I would accept a PR that adds the link to documentation, though. But keep in mind that this is a monorepo that contains multiple packages, and `parse5` is just one of them.

**Comment by Pomax** [comment]
I'm sorry, I don't see the problem? Is the issue that you need every centered? Because that seems... irrelevant for a decent readme? It's your call of course but then maybe call it readme.html since it's just an html file instead of a normal markdown file.

**Comment by inikulin** [comment]
What I'm trying to say is that I don't understand what this change intended to improve. I see regression in how markdown is displayed. Also, I don't understand reasoning behind: the PR removes HTML elements from the README justifying it by the usage of the "actual" markdown. Though, it's worth mentioning that HTML is a subset of markdown. 

> Anyway, the link is there, should be a few seconds work for you to add it in the original HTML form.

True, but I didn't open this PR.

**Comment by Pomax** [comment]
mostly it turned "not an md file" into an md file, but if you want to keep it html without renaming, that's your call. As for "True, but I didn't open this PR.", equally true but that keeps https://github.com/inikulin/parse5/issues/295 open of course, which you can probably resolve in a few seconds since you own the code and can just add in the link in the format you want instead directly without even needing a PR.

**Comment by inikulin** [comment]
> probably resolve in a few seconds since you own the code and can just add in the link in the format you want, without even needing a PR, using the github "edit file" option.

This indeed shouldn't take long. Though, you probably don't realise that parse5 is just one of my projects. I have 5 projects that I'm actively working at the moment and a few dozens that require my attention from time to time. With that in mind, it's sometimes quite hard for me to even find these few minutes to not harm my work-life balance. 

After all, it's a FOSS project, so anyone can contribute this change if it really bothers them.

**Comment by Pomax** [comment]
I have dozens of projects I'm part of as well, so I know the pain of wanting to work on something but literally never getting to it. I'll see if I can find some time to file a new PR instead.

**Pull request closed without merging**
