### PR TITLE
fix(serializer): safe use of replace

### PR DESCRIPTION
**Pull request by teleaziz**
when server-rendering angular2 apps using angular/universal I get str.replace is not a function error, debugging lead me here

### CODE REVIEW

**Comment by domenic** [comment]
It would be more interesting to find the bug in the code that was passing this a non-string. Parse5 seems correct.

**Comment by gdi2290** [comment]
Parse5 is correct you don't need to merge. The code for Universal is not ensuring the property is a string when setting the attribute. The bug showed up when we started to convert DOM properties to attributes since users weren't realizing that they should be setting attributes for DOM APIs.

see fix https://github.com/angular/universal/pull/567 in Angular Universal

**Comment by teleaziz** [comment]
glad you guys figured it out at universal, I still think type checking is necessary here as well.

**Comment by domenic** [comment]
There is type checking! It throws a TypeError if you pass the wrong type :)

**Pull request closed without merging**
