### PR TITLE
Add documentation for `template` tag

### PR DESCRIPTION
**Pull request by samouri**
While using `parse5` with `<template>` tags, I noticed that the content field is undocumented

### CODE REVIEW

**Comment by samouri** [comment]
@inikulin  / @anko: is this package still maintained?

**Comment by anko** [comment]
I don't know anything, I'm just some random person who fixed 1 bug I ran into! :smile:

**Comment by RReverser** [comment]
> 
> 
> @inikulin / @anko: is this package still maintained is this change ok?

Can't find his comment right now but @inikulin wrote somewhere that he doesn't have much time to maintain it at the moment and was looking for maintainers.

@inikulin perhaps worth adding that to the README?

**Comment by fb55** [comment]
Thanks a lot @samouri!

**Pull request merged**
