### PR TITLE
Use domhandler node interface in htmlparser2 adapter

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/cheeriojs/cheerio/issues/1506

cc @fb55 @inikulin

### CODE REVIEW

**Comment by TrySound** [comment]
Tests are passing locally.

**Comment by fb55** [comment]
Looks great 👌 

You might have to update the package-lock file for CI to pass.

**Comment by TrySound** [comment]
I guess I could but it's in gitignore for some reason

**Comment by TrySound** [comment]
Btw do you use npm 7 or 6?

**Comment by fb55** [comment]
The lock file is has a version of 1, which is npm 6.

**Comment by TrySound** [comment]
Caz adapter package does not have package-lock.json. And root one does not reflect workspaces. Yarn would work here. Probably npm 7 as well but I never tried it.

**Comment by TrySound** [comment]
Ah, perhaps the problem is that travis uses npm 7 :)

**Comment by fb55** [comment]
True, very interesting. @inikulin can hopefully provide some background infos.

**Comment by TrySound** [comment]
Travis changed their oss plan. A lot of builds are screwed up and take hours to finish. Perhaps they forces users to migrate to github actions and leave them alone.

**Comment by fb55** [comment]
> Travis changed their oss plan recently

I found out yesterday that all that's needed is a migration from Travis' .org offering to their .com domain. Builds seem to be fast again once that's done.

**Comment by fb55** [comment]
@inikulin Any feedback on this change? I'd love to get out a new release of cheerio, and this is currently blocking.

**Comment by frank-dspeed** [comment]
@fb55 i am at present doing a large refactor i will implement that directly now into the new version

**Comment by fb55** [comment]
@frank-dspeed Very cool, let me know if you need any help!

**Comment by inikulin** [comment]
Hi folks. Unfortunately I don't have enough time anymore to actively support the project. So, would love to see more co-maintainer. @fb55 maybe you'd like to take over the project? Would appreciate if you spread the word and contact me via ivan@nikulin.engineering

**Comment by fb55** [comment]
@inikulin Thanks for your offer — I am happy to take over the project! I've sent you an email a few weeks back; my one ask would be to transfer the project to the @cheeriojs org (or its own org), to encourage others to contribute to the project.

Please let me know if there is anything I can do to make this easier for you!

**Comment by fb55** [comment]
Thanks again for opening this @TrySound! Took a while to get this merged, but we are finally there.

**Pull request merged**
