### PR TITLE
Fix couple of mistakes in TreeAdapter API docs

### PR DESCRIPTION
**Pull request by RReverser**
(There is something weird going on with Github diff - the actual changed lines are not the ones it shows)

### CODE REVIEW

**Comment by RReverser** [comment]
What's even more weird, while https://github.com/RReverser/parse5/commit/c2f8f4f538aa6c6ed60ebc38e8c28af60f11f6d7 shows incorrect diff, https://github.com/RReverser/parse5/commit/c2f8f4f538aa6c6ed60ebc38e8c28af60f11f6d7.diff returns the correct one. Apparently there is some bug with Github.

**Comment by inikulin** [comment]
Thank you!

**Comment by RReverser** [comment]
@inikulin You're welcome. One more thing - either due to merge or I missed smth, but table got broken :( https://github.com/inikulin/parse5/blob/master/docs/05_api_reference.md#treeadaptersetdocumenttypedocument-name-publicid-systemid

**Comment by RReverser** [comment]
Likely forgot those two spaces in the end of some line(s).

**Pull request merged**
