### PR TITLE
Location info for Attributes (2.0)

### PR DESCRIPTION
**Pull request by yyx990803**
This is based on the work by @sakagg in #59 , with additional changes that:

- based off the latest 2.0 master;
- attrs location info attached to both `node.__location` and `node.__location.startTag`, as suggested in [this comment](https://github.com/inikulin/parse5/pull/59#issuecomment-130285405);
- fixed and ran the regression benchmark with the following result (no significant perf regression):

screen shot 2016-01-04 at 9 16 40 pm

### CODE REVIEW

**Comment by inikulin** [comment]
This is awesome, thank you! Could you please update docs as well?

**Comment by stevenvachon** [comment]
:+1:

**Comment by yyx990803** [comment]
@inikulin for docs, do you think it's sufficient just adding `attrs` to the base [LocationInfo](https://github.com/inikulin/parse5/wiki/Documentation#locationinfo--object) type?

**Comment by inikulin** [comment]
@yyx990803 Well, it's a little bit tricky. It requires new type `TagLocationInfo` that will extend `LocationInfo`, but will contain `attrs` as well. Meanwhile `startTag` and `endTag` in `ElementLocationInfo` should have `TagLocationInfo` type now. And we need to update references to the `LocationInfo` there `TagLocationInfo` meant.

**Comment by yyx990803** [comment]
Updated docs - my editor seems to have auto-converted all the `^M` chars into newlines, hence the big diff. Not sure if that is important though.

**Comment by inikulin** [comment]
@yyx990803 My bad, forgot to tell you to update jsdoc comments instead of `05_api_reference.md` since it's auto-generated. (I thought I've already removed this file from repo to avoid confusion, but seems like something went wrong =)). Really sorry for this.

**Comment by inikulin** [comment]
However, nevermind. I'll take care of this. Thank you!

**Comment by yyx990803** [comment]
cool, thanks!

**Comment by inikulin** [comment]
Published along with #91 as `v2.1.0`

**Pull request merged**
