### PR TITLE
Move entire codebase to ESM

### PR DESCRIPTION
**Pull request by 43081j**
Here i've moved the whole codebase to be written as ES modules.

This would be a huge breaking change. I have dropped all commonjs support.

This also resulted in fixing several bugs and bad tests that went unnoticed with CJS.

The aim here is to do another separate change which also moves the whole repo to typescript.

Again, this is a massive breaking change, completely backwards-incompatible by choice. If you don't want it, that is perfectly fine, i can keep it in a fork. If there's any changes and you want to help get it back into this repo, though, im happy to discuss/change whatever.

FYI all tests pass in its current state.

Note also, this probably _will not_ work in browsers. I'd love a world where node can handle true ESM, but it can't. This relies on node-only interop so our dependencies work (as our dependencies still use commonjs). In order to have a true esm codebase, all dependencies would also need to migrate.

cc @inikulin

### CODE REVIEW

**Comment by 43081j** [comment]
im still not following, why would a bundler struggle with a named export? webpack, rollup, esbuild, etc handle named exports just fine afaik. does one of you have a concrete example of some situation that won't work with a named export?

**Comment by Konakona-chan** [comment]
@43081j , thank you for your answer (yeah, I see the pull-request is kind of stale, unfortunately)!

Just a note: after changing [only one line](https://github.com/syntax-tree/hast-util-raw/blob/main/lib/index.js#L70) this pull-request works great (well, I haven't seen any issue yet) in svelte/vite/unifiedjs ESM-only project. Good luck with reviewers in this pull request or forking.

**Comment by fb55** [comment]
The benchmark script still had some broken imports; see https://github.com/parse5/parse5-fork/commit/f8afdbb8210fe80814d6463e6beb23dfe8298ed4 for a fix.

**Comment by 43081j** [comment]
good catch, have pushed a fix

**Comment by fb55** [comment]
@43081j I have created a fork at https://github.com/parse5/parse5-fork the other day, and have invited you to join it. This PR, plus some other small updates, are already on `master`.

I have created a discussion of what to do with the fork at https://github.com/parse5/parse5-fork/discussions/2 — let's discuss next steps there.

**Comment by fb55** [comment]
Thanks for this @43081j!

**Comment by domenic** [comment]
Oh, this is a shame. So jsdom cannot depend on parse5 anymore?

**Comment by fb55** [comment]
Hi @domenic, just for context: Could you summarise the stance of jsdom with regards to ESM? I am generally okay with delaying ESM in parse5 if this is a blocker somewhere else.

**Comment by domenic** [comment]
jsdom has many CommonJS-only dependencies, so it will be CommonJS until all of its dependencies update and the maintainers have time for a conversion. It'd be much preferable if this package supported CommonJS (e.g. via one of the techniques [here](https://2ality.com/2019/10/hybrid-npm-packages.html) until that time; it seems like the only way that we're going to be able to move the ecosystem is with such hybrid strategies.

**Comment by fb55** [comment]
Makes sense. I've opened #379 to track this.

**Comment by wooorm** [comment]
I can understand wanting to stick with CJS, but I don’t quite get this argument:

> so it will be CommonJS until all of its dependencies update

You want to wait for *all users of JSDOM* to use ESM or dual, before JSDOM can switch to ESM? 🤔 I find that a weird argument, because:
- the same argument could be used for any breaking change but JSDOM is at v19 already
- some dependents of open source are abandoned / will never receive updates, so it’s not possible to ever reach 100%?

---

What about these alternatives:

- JSDom can use ESM-only packages, with a dynamic import. It matches your [`engines`](https://github.com/jsdom/jsdom/blob/a604d67995fe5b2b1ce73090d347c23eeed011eb/package.json#L114). It does require asyncness though, unfortunately.
- JSDOM can ship a bundled CJS version of parse5, quickly generated with esbuild

**Comment by 43081j** [comment]
@domenic is right though, in that until JSDOM's dependencies are also ESM, jsdom isn't _technically_ ESM (it'd depend on node interop).

jsdom could deliver a CJS bundle, but its still a pretty big chunk of work for them to convert their codebase to ESM.

old unmaintained packages tend to get replaced soon enough, fortunately. but its true thats often a blocker for moving to ESM if there's no replacement.

we could temporarily ship a CJS bundle until consumers have had time to move, that isn't difficult (have two tsc configs or use a bundler to convert it back to commonjs).

**Comment by domenic** [comment]
>  i can't see us introducing any extra features anyway so @domenic could probably pin to 6.x

Well, several of the issues targeted for 7.0 per #330 add new features requested by me for jsdom specifically. Namely #332, #333, and #230.

**Comment by domenic** [comment]
> You want to wait for all users of JSDOM to use ESM or dual, before JSDOM can switch to ESM?

No. I need to wait for all *dependencies* of jsdom to use ESM or dual.

**Comment by wooorm** [comment]
> I need to wait for all *dependencies* of jsdom to use ESM or dual

As parse5 is a dependency of jsdom, and you are waiting for dependencies to use ESM or dual, then why do you now not want parse5 to become esm?

> Because ESM packages cannot depend on non-ESM packages without making package startup async

Could you elaborate? I have experience with ESM packages in native Node.js that use CJS, dual, and ESM dependencies with sync import statements.
And CJS packages that can only use ESM dependencies with dynamic `import()` expressions.

> #332, #333, and #230.

What if those also land on the current (CJS) version? (And future security stuff of course)

**Comment by 43081j** [comment]
@domenic totally missed those issues, my bad.

tbh i think we should just create a CJS bundle at build time until everyone's moved over. we don't want to block each other's progression to ESM and its a very simple thing for us to add.

**Pull request merged**
